Resources:
    RedeemDynamoDBTable:
        Type: "AWS::DynamoDB::Table"
        Properties:
            BillingMode: PAY_PER_REQUEST
            TableName: ${self:provider.environment.REDEEM_TABLE}
            AttributeDefinitions:
                - AttributeName: userId
                  AttributeType: S
                - AttributeName: createdAt
                  AttributeType: S
            KeySchema:
                - AttributeName: userId
                  KeyType: HASH
                - AttributeName: createdAt
                  KeyType: RANGE